### PR TITLE
Add TeamCity DSL

### PR DESCRIPTION
**Pull request by dmitry-treskunov**
Adding TeamCity build

### CODE REVIEW

**Comment by pavel-github** [comment]
@adrukh, LGTM.
@dmitry-treskunov, only one question: any way to use maven wrapper (`./mvnw clean package`) or we can use bundled Maven versions only?

**Comment by dmitry-treskunov** [comment]
It's possible to use maven wrapper using a command line runner instead of maven runner. 
I can do it if you want

**Comment by pavel-github** [comment]
It would be great, so the build process will exact the same as in Travis.
Can you use `./mvnw clean verify` in case we add integration tests later? Thanks

**Comment by pavel-github** [comment]
@adrukh, 👍 LGTM. We can merge this PR.

**Comment by adrukh** [comment]
Thanks folks!

How should we version this? I’m ok starting with 1.0.0.

**Review by adrukh — APPROVED** [review]

**Pull request merged**
